# for properties see http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

siteName: kalipo

server:
    port: 8080

spring:
    profiles: dev
    data:
        mongodb:
            host: localhost
            port: 27017
            databaseName: kalipo


    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false
        viewNames: error

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M

# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
      project: org.kalipo
      domain: org.kalipo.domain
      restdto: org.kalipo.web.rest.dto
    watchdir:
      - target/classes
